# coding: utf-8

# Triangular, pentagonal, and hexagonal
# Problem 45
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

def triangle_series(n):
    while True:
        yield n * (n + 1) // 2
        n += 1

def pentagonal_series(n):
    while True:
        yield n * (3 * n - 1) // 2
        n += 1

def hexagonal_series(n):
    while True:
        yield n * (2 * n - 1)
        n += 1

def solve():
    tn = 286
    pn = 166
    hn = 144

    triangle = triangle_series(tn)
    pentagonal = pentagonal_series(pn)
    hexagonal = hexagonal_series(hn)
    h = p = t = 40755
    while True:
        h = next(hexagonal)

        while p < h:
            p = next(pentagonal)

        while t < h:
            t = next(triangle)

        if h == p and t == h:
            return h

if __name__ == '__main__':
    print(__file__ + ": %d" % solve())
